deeporiginbio/deeporigin-client

README.md
src/managed_data/api.py
src/managed_data/schema.py
tests/test_managed_data.py

fix(docs): cleaned up readme

---

.github/workflows/main.yml
Makefile
sonar-project.properties
src/managed_data/_api.py
src/managed_data/api.py
src/managed_data/client.py
src/managed_data/schema.py
tests/test_managed_data.py

fix(infra): better install and better sonarcloud runs

---

src/__init__.py

- fixed a bug where version number wasn't being correctly described if imported from a directory that wasn't the root of the code.

fix(managed-data): fixed a bug in dynamic git version

---

Makefile

Closes https://formiclabs.atlassian.net/browse/DOS-1752

feat(infra): avoided error messages in repeated installations

---

src/__init__.py
src/cli/data.py
src/managed_data/api.py
tests/test_managed_data.py

fix(managed-data): fixed a bug with multiple root items

---

README.md
src/cli/data.py
src/managed_data/api.py

fix(managed-data): many small improvements

---

.github/workflows/main.yml
Makefile
pyproject.toml
scripts/build_docs.sh
src/cli/__init__.py
src/cli/context.py
src/cli/data.py
src/cli/variables.py
src/context.py
src/managed_data/_api.py
src/managed_data/api.py
src/managed_data/client.py
src/managed_data/schema.py
src/utils.py
src/variables/types/anthropic_api_key.py
src/variables/types/open_ai_api_key.py
tests/test_cli_data.py
tests/test_managed_data.py

feat(managed-data): support for more functionality

---

.github/workflows/docs.yaml
.github/workflows/main.yml
README.md

feat(docs): added pypi badge

---

.github/workflows/docs.yaml
.github/workflows/main.yml
docs/how-to/config.md
docs/how-to/do-info.md
docs/how-to/variables.md
mkdocs.yaml

fix(docs): added info about variables

---

MANIFEST.in
Makefile
README.md
pyproject.toml
src/managed_data/_api.py
src/managed_data/api.py
src/managed_data/client.py
src/managed_data/schema.py
tests/test_managed_data.py

fix(managed-data): improvemented to managed-data

---

src/config/default.yml

Closes [DOS-2333](https://formiclabs.atlassian.net/browse/DOS-2333)
[DOS-2333]: https://formiclabs.atlassian.net/browse/DOS-2333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: set default configuration to production settings

---

src/managed_data/api.py

- fixes a bug where empty rows were skipped
- types many columns in pandas dataframes

Dataframe improvements

---

.github/CODEOWNERS
README.md
docs/install.md
mkdocs.yaml
tests/mock_client.py

change to go along with org rename 
tests will probably fail before the rename.

fix: renamed formiclabs to deeporiginbio

---

src/managed_data/client.py

We want to be able to use the client in contexts where:
- we don't have write access to the filesystem
- where the config file doesn't exist
- where we want to use the client to connect to different resources than specified in the config file
- we don't want to make any authentication requests, we already have a hot token
to solve all these problems, it should be possible to do something like this:
```python
from deeporigin.managed_data.client import DeepOriginClient
client = DeepOriginClient(api_url="foo", org_id="bar")
client.authenticate(token="token")
```

feat(client): client can now be configured without config files

---

src/managed_data/client.py

small bugfix where the client wasn't being configured correctly

fix: fixed client not having the right props

---

Makefile
docs/how-to/managed-data/upload-data.md
docs/index.md
src/cli/data.py
src/managed_data/_api.py
src/managed_data/schema.py

feat: expanded docs to talk about uploading files

---

Makefile
docs/how-to/managed-data/upload-data.md
docs/how-to/managed-data/write-data.md
mkdocs.yaml
src/cli/data.py
src/managed_data/_api.py
src/managed_data/api.py
src/managed_data/client.py
src/managed_data/schema.py
tests/mock_client.py
tests/test_managed_data.py

Support for uploading data 

---

src/data_hub/api.py

small bugfix where get_dataframe would fail if HID has a `-` in it

fix: fixed a bug in get_dataframe where HID prefix had a -

---

src/data_hub/api.py

- ability to write data to many cells at once with a single function/API call
- body document columns now not included in dataframe

fix: many small fixes to python client

---

docs/configure.md
docs/how-to/config-package.md
docs/how-to/data-hub/upload-files.md
docs/how-to/data-hub/view-data.md
docs/install.md
docs/ref/data-hub/low-level-api.md
mkdocs.yaml
src/data_hub/api.py
src/utils.py

Updates to documentation and bugfixes

---

src/data_hub/_api.py
src/utils.py

Minor improvements and bug fixes

---

docs/compute-hub/index.md
docs/configure.md
docs/data-hub/index.md
docs/how-to/auth.md
docs/how-to/data-hub/create.md
docs/how-to/data-hub/delete.md
docs/how-to/data-hub/list-data.md
docs/how-to/variables.md
mkdocs.yaml
src/auth.py
src/cli/data.py
src/cli/variables.py
src/data_hub/api.py
src/variables/base_type.py
src/variables/core.py
src/variables/types/aws_profile.py
src/variables/types/env_var.py

- platform -> OS
- workspace -> folder
- Normalize capitalization of data hub, compute hub, workstation, Python
- Lint: removed trailing spaces and consecutive blank lines in docs

feat(docs): minor edits to docs

---

src/data_hub/api.py

fix: fixed some small bugs

---

docs/changelog.md
docs/data-hub/dataframes.md
pyproject.toml
src/__init__.py
src/data_hub/api.py
src/data_hub/dataframe.py
src/utils.py

fix: number of small bugfixes with dataframes

---

src/data_hub/api.py

removed all parts of the hash computation in upload file

fix: we don't send the hash

---

pyproject.toml
src/auth.py
src/cli/context.py
src/cli/variables.py
src/context.py
src/data_hub/_api.py
src/exceptions.py
src/feature_flags.py
src/variables/base_type.py
src/variables/core.py
src/variables/types/anthropic_api_key.py
src/variables/types/aws_profile.py
src/variables/types/env_var.py
src/variables/types/file.py
src/variables/types/git_http_credentials.py
src/variables/types/gurobi_license_file.py
src/variables/types/mosek_license_file.py
src/variables/types/open_ai_api_key.py
src/variables/types/private_gpg_key.py
src/variables/types/private_ssh_key.py
src/variables/types/secret_env_var.py
src/variables/types/secret_env_var_value.py
src/variables/types/secret_file.py
src/variables/types/secret_file_value.py
src/variables/types/xpress_license_file.py
src/warnings.py

fix: added docstrings for all modules

---

.github/workflows/main.yml
src/platform/api.py
tests/test_variables.py

feat: ability to delete terminated workstations

---

.github/workflows/main.yml
Makefile
docs/configure.md
src/cli/data.py
src/data_hub/api.py
src/data_hub/dataframe.py
src/platform/api.py
tests/test_data_hub.py
tests/test_dataframe.py
tests/test_dataframe_kitchen_sink.py
tests/test_variables.py
tests/utils.py

fix: better typing for dataframes

---

Makefile
pyproject.toml
src/data_hub/plotting.py

https://github.com/user-attachments/assets/c8058090-9772-4083-872c-2f9379fbecd0

feat: ability to make plots from Deep Origin dataframes

---

Makefile
pyproject.toml
src/__init__.py
src/data_hub/dataframe.py
src/data_hub/plotting.py

fix: insertion of series data into dataframe

---

src/data_hub/axes_callback.js
src/data_hub/button_callback.js
src/data_hub/hover_callback.js
src/data_hub/plotting.py

fix: annotation improvements

---

.github/workflows/live_tests.yaml
src/data_hub/api.py
src/data_hub/dataframe.py

Live tests

---

src/data_hub/_api.py

small fix to handle text responses

fix: better handling of text responses

---

src/data_hub/api.py

at some point i used the ensure_client decorator to make sure functions always had a client that was configured correctly. this isn't needed because the low-level bridge code does this for us.

fix: removed ensure_client decorator

---

docs/tools/pdb-to-pdbqt.md
mkdocs.yaml
src/tools/run.py

feat: added pdb->pdbqt conferter

---

docs/tools/draco.md
src/tools/utils.py

update draco docs to latest version

feat: update draco docs

---

.github/workflows/pypi.yml

Adding comments in the process of learning our code and github actions.

core: added comments about PyPI actions

---

docs/install.md
docs/install.sh

added details on how to upgrade an existing install

chore: update docs

---

src/drug_discovery/docking.py
src/drug_discovery/utils.py
src/tools/utils.py
src/utils/notebook.py

feat: support for progress reporting in docking

---

src/drug_discovery/utils.py
src/tools/job.py
src/tools/run.py
src/tools/utils.py

feat: ability to cancel jobs

---

src/drug_discovery/abfe.py

fix: failed abfe jobs are now correctly rendered

---

src/drug_discovery/abfe.py
src/files/files_client.py
src/templates/job.html
src/tools/job.py
tests/files_manual_test_remote.py

https://github.com/user-attachments/assets/09f822d8-b351-4f5a-9597-e9844b7ad6ff

Better job views

---

src/auth.py
src/data_hub/_api.py
src/platform/api.py

Token checks

---

src/drug_discovery/docking.py
src/drug_discovery/workflow_step.py
src/tools/job.py
src/utils/notebook.py

feat: progress bar for docking

---

MANIFEST.in
src/drug_discovery/docking.py
src/tools/run.py

Docking improvements

---

src/auth.py
src/drug_discovery/complex.py
src/drug_discovery/docking.py
src/tools/utils.py

Abfe job bugfixes

---

src/drug_discovery/abfe.py
src/drug_discovery/utils.py
src/json/abfe_end_to_end.json
src/tools/job.py

Download data abfe

---

.gitignore
notebooks/abfe.py
notebooks/ligand.py
notebooks/protein.py
src/drug_discovery/abfe.py
src/drug_discovery/complex.py
src/drug_discovery/structures/ligand.py
src/drug_discovery/workflow_step.py
src/templates/job.html
src/tools/job.py
src/utils/notebook.py

Demo polish

---

src/drug_discovery/abfe.py
src/platform/tools_api.py

this PR introduces dynamically constructed functions that can call any tool

Files api fixes

---

src/drug_discovery/abfe.py
src/drug_discovery/complex.py
src/drug_discovery/external_tools/utils.py
src/functions/sysprep.py
tests/test_dd_utils.py
tests/test_functions.py

feat: support for sysprep

---

src/drug_discovery/complex.py
src/drug_discovery/docking.py
src/drug_discovery/utils.py
src/platform/tools_api.py
src/tools/job.py

docking now uses UFA to handle files

feat: docking now uses UFA

---

MANIFEST.in

fixed a bug where the files client was non functional due to a missing file

fix: include YAML file in MANIFEST.in

---

src/drug_discovery/abfe.py
src/drug_discovery/rbfe.py
src/drug_discovery/utils.py
src/json/rbfe_end_to_end.json
src/platform/tools_api.py

feat: Ability to run RBFE using UFA

---

.vscode/settings.json
docs/dd/how-to/job-docking.html
docs/dd/how-to/job.md
docs/index.md
mkdocs.yaml
src/drug_discovery/abfe.py
src/drug_discovery/docking.py
src/drug_discovery/rbfe.py
src/drug_discovery/workflow_step.py
src/templates/job_jupyter.html
src/tools/job.py
src/tools/job_viz_functions.py

Job improvements

---

src/drug_discovery/docking.py
src/drug_discovery/workflow_step.py
src/platform/tools_api.py
src/platform/utils.py
src/tools/job.py

Docking fixes 8

---

src/drug_discovery/structures/protein.py

we can now show a ligand with a protein like
```python
protein.show(ligand=ligand)
protein.show(ligands=ligands)
```

feat: support for showing ligands with proteins

---

src/drug_discovery/abfe.py
src/platform/file_api.py
src/platform/utils.py

- sim.abfer.get_results now works

Abfe results

---

pyproject.toml
src/drug_discovery/structures/pocket.py
src/utils/constants.py
tests/test_pocket.py
tests/test_tools_api.py

Expand testing

---

docs/dd/how-to/job.md
src/platform/tools_api.py
src/templates/job_jupyter.html
src/tools/job.py
src/utils/constants.py
tests/test_tools_api.py

- fixed a bug where job widget mixed up IDs
- rolled back to old version of job widget because the new one had weird CSS issues
- support for new terminal states

feat: support for new terminal states
