- .github/workflows/main.yml
- src/config/__init__.py
- src/managed_data/client.py
- tests/test_config.py
- tests/test_variables.py
- [] ~~allow overriding of environment file with config file~~
[no longer valid: not doing this]
i've changed the order of operations so that config file overrides environment variables. the reason for this is because on compute benches, environment variables are baked in and never change once jupyter lab starts. so once a bench is running, it is not possible to change env variables that are read by the client. and because env variables override files (previously), it was impossible to change any settings for the client.
> fix(testing): added windows tests

- tests/test_config.py
(ignore the check that is pending -- it's not really a check)
> fix(testing): re-enabled test on windows

- src/variables/core.py
- src/variables/types/env_var.py
- tests/test_cli.py
- tests/test_variables.py
as part of the renaming of this CLI, from deep-origin to deeporigin, we forgot to change where variables were being stored. this has now been fixed.
> fix(CLI): fixed a bug where `deep-origin` was still being used

- src/auth.py
- src/config/__init__.py
the client now attempts to read access tokens from the env, if it exists, before trying to read from disk or asking the user to authenticate.
> feat: supports reading tokens from env

- src/__init__.py
- src/config/__init__.py
when running in lambda, reading a config file fails for some unknown reason. 
we shouldn't be reading a config file anyway, introduced a shortcut to read from envs directly
> feat: shortcut when running in AWS lambda; read config values from env

- Makefile
- pyproject.toml
- src/auth.py
- src/cli/__init__.py
- src/cli/config.py
- src/config/__init__.py
- src/exceptions.py
- src/managed_data/_api.py
- src/managed_data/api.py
- src/managed_data/client.py
- src/variables/core.py
- src/variables/types/aws_profile.py
- tests/mock_client.py
- tests/test_config.py
- tests/test_managed_data.py
```
❯ deeporigin config load prod
✔︎ Configuration loaded from /Users/srinivas/.deeporigin/prod.yml
```
pretty errors:
```
❯ deeporigin data list
╭──────────────────────────────────────────────────────────────────────╮
│ Invalid configuration                                                │
├──────────────────────────────────────────────────────────────────────┤
│ The Deep Origin CLI and python client requires a valid configuration │
│ file. This field is not valid:  organization_id: must be a string    │
├──────────────────────────────────────────────────────────────────────┤
│ To fix, run `deeporigin config set organization_id <value>`          │
╰──────────────────────────────────────────────────────────────────────╯
```
> fix: dataframe better matches DB

- docs/how-to/do-info.md
- pyproject.toml
- src/cli/context.py
- src/context.py
- src/managed_data/_api.py
- src/managed_data/schema.py
- tests/test_context.py
`deeporigin context` is intended to print out information including
- The compute cluster where the bench is being run. This is to help developers, such as molecular modeling, communicate with other containers.
- Hardware. This is to provide users, such as molecular modeling, accurate information about the resources of the bench. This is important because the Linux commands for reporting memory don't work as expected in containers in shared hosts.
This PR disables printing this information because the platform no longer provides this information. [DOS-3008](https://deeporiginbio.atlassian.net/browse/DOS-3008) will add it. Until that point, we should avoid printing unsupported information.
Rather than deleting support for this information in this library, I instead refactored the library …
> feat: disabled printing context for compute cluster and hardware which the platform no longer provides

- docs/how-to/data-hub/delete.md
- pyproject.toml
- src/cli/data.py
@kennyjwilli made a breaking change to the API and the syntax for deleting columns now requires us to specify database ID
> feat: updated to new version of deleting database columns

- src/data_hub/api.py
If the `file_ids` length is 0, there is no reason to execute the `ListFiles` operation.
> fix: check `file_ids` length prior to listing files

- docs/data-hub/dataframes.md
- pyproject.toml
- src/data_hub/api.py
- src/data_hub/dataframe.py
- src/platform/api.py
previously this behavior existed, where printing a dataframe worked, but using df.head() would trigger a spurious warning about dataframes containing modified data
this was because this was technically correct -- pandas df.head() created a shallow copy of a dataframe, which was technically a new object, and because the data in the new dataframe was not the same, the warning was shown.
however, this is useless and misleading from an end user persp. so we override these methods.
> fix: more bugfixes & improvements

- .github/workflows/main.yml
- src/data_hub/_api.py
expired tokens were correctly being intercepted and a new token was being obtained, but the functools.cache decorator on one of the functions was preventing us from reading the new token on disk, and instead relying on a cached token (cached in memory).
this led to a bug where the warning about expired tokens never went away (unless you reloaded and reimported)
> fix: fixed a bug where expired tokens were not being refreshed

- src/data_hub/api.py
- src/data_hub/dataframe.py
- src/platform/api.py
- src/utils/network.py
previously, using the AI assistant would surface this message, which cannot be acted upon because the user can't upgrade the client
> fix: suppress message about new version on lambda

- Makefile
- src/data_hub/dataframe.py
- tests/test_dataframe.py
- tests/test_dataframe_kitchen_sink.py
- ability to write data back to DB when adding new rows
- support for appending a pandas dataframe
> feat: slicing a dataframe using `loc` preserves attributes

- docs/CNAME
the custom domain keeps getting reset, and this is the supposed fix
https://github.com/tschaub/gh-pages/pull/375/commits/1e38a134d29b6c8104e74fdb6a4fb5201f65f49c
see also:
https://stackoverflow.com/questions/67183664/why-is-my-github-pages-custom-domain-constantly-reset
> fix: attempt to fix custom domain reset

- .github/workflows/live_tests.yaml
tests against a live instance (that were configured to run daily) were broken because the access token kept going stale. 
this PR fixes this by manually refreshing before running tests. 
https://github.com/deeporiginbio/deeporigin-client/actions/runs/12014629544
> fix: only patch the action

- src/data_hub/api.py
- tests/fixtures/responses/convert_id_format.json
- tests/fixtures/responses/create_database.json
- tests/fixtures/responses/create_file_upload.json
- tests/fixtures/responses/create_workspace.json
- tests/fixtures/responses/describe_database_stats.json
- tests/fixtures/responses/describe_row.json
- tests/fixtures/responses/ensure_rows.json
- tests/fixtures/responses/list_database_rows.json
- tests/fixtures/responses/list_files.json
- tests/fixtures/responses/list_rows.json
- tests/test_data_hub.py
- removed `download_file`
- refactored rest of code to use `download_files`
> fix: removed download_file

- docs/how-to/tools/list-tools.md
- docs/how-to/tools/run-tools.md
- docs/tools/index.md
- docs/tools/vina.md
- mkdocs.yaml
- pyproject.toml
- src/platform/clusters.py
- src/tools/autodock_vina.py
- src/tools/utils.py
> feat: tooling to run autodock vina on deep origin

- src/config/default.yml
reverting auth_domain to what it was before, because this is the only way it works with both data hub + platform
> fix: reverting change in auth_domain

- .github/CODEOWNERS
- Makefile
- pyproject.toml
- src/tools/run.py
- src/tools/toolkit.py
- tests/test_cli_config.py
- tests/test_cli_data.py
```py
from deeporigin.tools import toolkit
csv_file = "/Users/srinivas/Downloads/ligands.csv"
column_name = "SMILES"
toolkit.prep_ligands(
csv_file=csv_file,
column_name=column_name,
)
```
^ this takes in a CSV file, converts every smiles string to a SDF file, uploads them to datahub, and preps them all using meeko (on deeporigin)
```py
ligand_database_name = "ligand-prep-meeko"
ligand_column_name = "output-ligand"
protein_database_name = "protein"
protein_column_name = "protein"
protein_row = "protein-1"
search_space = {
"center_x": 15.190,
"center_y": 53.903,
"center_z": 16.917,
"size_x": 15.1,
"size_y": 15.1,
"size_z": 15.1,
}
docking = {
"energy_range": 3.1,
"exhaustiveness": 1,
"num_modes": 3,
}
toolkit.dock_ligands_to_protein(
docking=docking,
search_space=search_space, …
```
> feat: high level toolkit for running ligand and docking

- docs/changelog.md
- docs/dd/how-to/complex.md
- docs/dd/how-to/filter-docking-outputs.md
- docs/dd/how-to/ligands.md
- docs/dd/how-to/use-docking-outputs-for-fep.md
- docs/dd/how-to/visualize.md
- docs/dd/tutorial/docking.md
- docs/dd/tutorial/getting-started.md
- mkdocs.yaml
- src/drug_discovery/chemistry.py
- src/drug_discovery/complex.py
- src/drug_discovery/docking.py
- tests/test_chemistry.py
> feat: improvements to docking tools

- pyproject.toml
- src/drug_discovery/abfe.py
- src/tools/job.py
- src/tools/utils.py
> feat: named runs for ABFE

- src/utils/core.py
This pull request simplifies the directory creation logic in the `_ensure_do_folder` function within `src/utils/core.py`, and should fix the problem of concurrent execution of `_ensure_do_folder`.
Code improvement:
* [`src/utils/core.py`](diffhunk://#diff-6dd63dcba1e65fa1db77ad1cdc2cc81450272b70ba50d1825d752017aa26615bL471-R471): Replaced the conditional check for directory existence and creation with a single call to `mkdir` using the `exist_ok=True` parameter, which ensures the directory is created if it doesn't exist and avoids redundant checks.
> Updated scratch folder creation to respect concurrent runs.

- src/drug_discovery/structures/protein.py
- src/functions/docking.py
- src/functions/loop_modelling.py
- src/functions/molprops.py
- src/functions/pocket_finder.py
- src/functions/sysprep.py
- src/utils/core.py
- tests/test_functions.py
- tests/test_utils.py
- tests/utils.py
> chore: refactored functions to use a common hashing strategy
